export const COPING_ALPHABET = [
    { letter: 'A', action: 'Ask for help', icon: 'help-circle', wrong: ['Abacus is fun', 'Anybody can dance'] },
    { letter: 'B', action: 'Breathe deeply and slowly', icon: 'wind', wrong: ['Balloons are bouncy', 'Bananas are yellow'] },
    { letter: 'C', action: 'Count forwards or backwards', icon: 'hash', wrong: ['Cats like cucumbers', 'Clouds are cotton candy'] },
    { letter: 'D', action: 'Drink some cold water', icon: 'droplet', wrong: ['Dinosaurs like donuts', 'Ducks go quack'] },
    { letter: 'E', action: 'Exercise - Run, jump, skip', icon: 'activity', wrong: ['Elephants eat eggs', 'Every egg is oval'] },
    { letter: 'F', action: 'Find a safe place', icon: 'home', wrong: ['Fish can fly', 'Frogs can\'t frown'] },
    { letter: 'G', action: 'Go to your happy place', icon: 'map-pin', wrong: ['Giraffes have green glasses', 'Goats go gallivanting'] },
    { letter: 'H', action: 'Hug a friend or family member', icon: 'heart', wrong: ['Hippos hide hats', 'Horses have hobbies'] },
    { letter: 'I', action: 'Ignore people who are annoying you', icon: 'user-x', wrong: ['Igloos in Italy', 'Ice cream is icy'] },
    { letter: 'J', action: 'Jokes to help you laugh', icon: 'laugh', wrong: ['Jellyfish join jokes', 'Juggling jelly beans'] },
    { letter: 'K', action: 'Kind hands, keep them to yourself', icon: 'hand', wrong: ['Kangaroos kick kitchens', 'Kittens know karate'] },
    { letter: 'L', action: 'Listen to calming music', icon: 'music', wrong: ['Lions love lemons', 'Llamas lick lollipops'] },
    { letter: 'M', action: 'Meditate - Use yoga or mindfulness', icon: 'brain', wrong: ['Mice make music', 'Monkeys match muffins'] },
    { letter: 'N', name: 'Name the emotion', action: 'Name the emotion you are feeling', icon: 'tag', wrong: ['Newts need notebooks', 'Nightingales nap nicely'] },
    { letter: 'O', action: 'Observe - use mindfulness techniques', icon: 'eye', wrong: ['Owls outsmart oranges', 'Octopuses order onions'] },
    { letter: 'P', action: 'Paint Your feelings', icon: 'palette', wrong: ['Penguins play piano', 'Pandas paint plants'] },
    { letter: 'Q', action: 'Question Your thoughts', icon: 'help-circle', wrong: ['Queens question quilts', 'Quails quicken quests'] },
    { letter: 'R', action: 'Run As fast as you can', icon: 'fast-forward', wrong: ['Rabbits read recipes', 'Robots run races'] },
    { letter: 'S', action: 'Separate yourself from the situation', icon: 'scissors', wrong: ['Snakes sell socks', 'Squirrels save seeds'] },
    { letter: 'T', action: 'Thoughts negative to positive', icon: 'refresh-cw', wrong: ['Turtles tell tales', 'Tigers taste tea'] },
    { letter: 'U', action: 'Use your safe place', icon: 'shield', wrong: ['Unicorns use umbrellas', 'Underwear is unique'] },
    { letter: 'V', action: 'Voice your concerns', icon: 'mic', wrong: ['Vultures visit villages', 'Vampires view vegetables'] },
    { letter: 'W', action: 'Write Down your feelings', icon: 'pen-tool', wrong: ['Whales wear wigs', 'Wolves watch windows'] },
    { letter: 'X', action: 'Exhale - Breathe out your feelings', icon: 'wind', wrong: ['X-rays xerox xylophones', 'Xenon x-rays x-mas trees'] },
    { letter: 'Y', action: 'Yell As loud as you can into a pillow', icon: 'volume-2', wrong: ['Yaks yell "Yippee!"', 'Yellow yo-yos yarn'] },
    { letter: 'Z', action: 'Zone out and relax yourself', icon: 'cloud', wrong: ['Zebras zigzag zoos', 'Zombies zap zucchinis'] }
];
